"""
============================================================
StudyAI Backend — Export Route
============================================================
GET /api/export/pdf — Export a study plan or summary to PDF
"""

from __future__ import annotations

import io
from flask import Blueprint, request, send_file, g

from middleware.auth_middleware import login_required
from services.firebase_service import StorageRouter
from utils.logger import get_logger

logger = get_logger(__name__)

export_bp = Blueprint("export", __name__)


@export_bp.get("/export/pdf")
@login_required
def export_pdf():
    """
    Export study plan or summary to a beautifully formatted PDF.
    Expects query parameters:
        type: "study-plan" | "summary"
        id: (optional) document ID. Latest active is used if omitted.
    """
    export_type = request.args.get("type", "study-plan")
    doc_id = request.args.get("id")
    
    logger.info("PDF export triggered. type=%s, id=%s, user=%s", export_type, doc_id, g.user_id)

    # ── Fetch active item ─────────────────────────────────
    if not doc_id:
        if export_type == "study-plan":
            items = StorageRouter("study_plans").filter_by_user(g.user_id)
            if not items:
                return {"success": False, "error": "No study plan found to export."}, 404
            items.sort(key=lambda x: x.get("created_at", ""), reverse=True)
            item = items[0]
        else:
            items = StorageRouter("summaries").filter_by_user(g.user_id)
            if not items:
                return {"success": False, "error": "No summaries found to export."}, 404
            items.sort(key=lambda x: x.get("created_at", ""), reverse=True)
            item = items[0]
    else:
        if export_type == "study-plan":
            item = StorageRouter("study_plans").get(doc_id)
        else:
            item = StorageRouter("summaries").get(doc_id)
            
        if not item:
            return {"success": False, "error": f"{export_type} not found."}, 404
            
        if item.get("user_id") != g.user_id:
            return {"success": False, "error": "Unauthorized access to this document."}, 403

    # ── Generate PDF via ReportLab ─────────────────────────
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40
        )
        
        styles = getSampleStyleSheet()
        story = []
        
        # Colors: SLEEK INDIGO (#4F46E5) & GRAY (#6B7280)
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            leading=28,
            textColor='#4F46E5',
            spaceAfter=15
        )
        subtitle_style = ParagraphStyle(
            'SubtitleStyle',
            parent=styles['Normal'],
            fontSize=10,
            textColor='#6B7280',
            spaceAfter=25
        )
        h2_style = ParagraphStyle(
            'H2Style',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor='#1F2937',
            spaceBefore=12,
            spaceAfter=8
        )
        body_style = ParagraphStyle(
            'BodyStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=15,
            textColor='#374151',
            spaceAfter=8
        )
        task_style = ParagraphStyle(
            'TaskStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=15,
            textColor='#374151',
            leftIndent=20,
            firstLineIndent=-10,
            spaceAfter=5
        )

        if export_type == "study-plan":
            subject = item.get("subject", "General Subject")
            exam_date = item.get("exam_date", "N/A")
            difficulty = item.get("difficulty", "medium")
            days = item.get("days", [])
            
            story.append(Paragraph(f"Study Plan: {subject}", title_style))
            story.append(Paragraph(f"Exam Date: {exam_date} | Difficulty: {difficulty.upper()} | Generated by StudyAI", subtitle_style))
            story.append(Spacer(1, 10))
            
            for day in days:
                date_str = day.get("date", "")
                tasks = day.get("tasks", [])
                completed = " (Completed)" if day.get("completed") else ""
                
                story.append(Paragraph(f"<b>Date: {date_str}</b>{completed}", h2_style))
                for task in tasks:
                    story.append(Paragraph(f"• {task}", task_style))
                story.append(Spacer(1, 10))
        else:
            title = item.get("document_title", "Untitled Summary")
            summary_content = item.get("summary", {})
            
            story.append(Paragraph(f"Study Summary: {title}", title_style))
            story.append(Paragraph("Generated by StudyAI summarization engine", subtitle_style))
            story.append(Spacer(1, 10))
            
            overview = summary_content.get("overview", "")
            if overview:
                story.append(Paragraph("Overview", h2_style))
                story.append(Paragraph(overview, body_style))
                story.append(Spacer(1, 10))
                
            key_points = summary_content.get("key_points", [])
            if key_points:
                story.append(Paragraph("Key Points", h2_style))
                for pt in key_points:
                    story.append(Paragraph(f"• {pt}", task_style))
                story.append(Spacer(1, 10))
                
            concepts = summary_content.get("important_concepts", [])
            if concepts:
                story.append(Paragraph("Important Concepts", h2_style))
                for concept in concepts:
                    term = concept.get("term", "")
                    definition = concept.get("definition", "")
                    story.append(Paragraph(f"<b>{term}</b>: {definition}", task_style))
                story.append(Spacer(1, 10))

        doc.build(story)
        buffer.seek(0)
        
        filename = f"{export_type}_{g.user_id[:6]}.pdf"
        logger.info("Successfully generated PDF: %s", filename)
        
        return send_file(
            buffer,
            as_attachment=True,
            download_name=filename,
            mimetype="application/pdf"
        )
        
    except Exception as exc:
        # Fallback to plain text if reportlab is not installed / fails
        logger.warning("ReportLab failed, falling back to plain text file: %s", exc)
        
        buffer = io.BytesIO()
        text_content = f"StudyAI Export — {export_type.upper()}\n"
        
        if export_type == "study-plan":
            subject = item.get("subject", "General Subject")
            exam_date = item.get("exam_date", "N/A")
            difficulty = item.get("difficulty", "medium")
            days = item.get("days", [])
            
            text_content += f"Subject: {subject}\nExam Date: {exam_date}\nDifficulty: {difficulty}\n"
            text_content += "=" * 50 + "\n\n"
            
            for day in days:
                text_content += f"Date: {day.get('date', '')}\n"
                for task in day.get("tasks", []):
                    text_content += f"  - {task}\n"
                text_content += "\n"
        else:
            title = item.get("document_title", "Untitled Summary")
            summary_content = item.get("summary", {})
            text_content += f"Summary Title: {title}\n"
            text_content += "=" * 50 + "\n\n"
            
            text_content += f"Overview:\n{summary_content.get('overview', '')}\n\n"
            
            text_content += "Key Points:\n"
            for pt in summary_content.get('key_points', []):
                text_content += f"  - {pt}\n"
            text_content += "\n"
            
            text_content += "Important Concepts:\n"
            for concept in summary_content.get('important_concepts', []):
                text_content += f"  - {concept.get('term', '')}: {concept.get('definition', '')}\n"
                
        buffer.write(text_content.encode("utf-8"))
        buffer.seek(0)
        
        filename = f"{export_type}_{g.user_id[:6]}.txt"
        return send_file(
            buffer,
            as_attachment=True,
            download_name=filename,
            mimetype="text/plain"
        )
